[project]
name = "pydep"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.0",
    "textual>=8.0.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.15.2",
]
